general:
  locale: en-US
  title: Sorensen Cloud

search:
  enabled: true
  provider: duckduckgo # google, duckduckgo

links:
  - name: Radarr
    url: http://radarr.internal.sorensen.cloud
  - name: Sonarr
    url: http://sonarr.internal.sorensen.cloud
    image: https://developer.asustor.com/uploadIcons/0020_999_1573625786_Radarr_256.png
  - name: Sabnzbd
    url: http://sabnzbd.internal.sorensen.cloud
    image: _logo/sabnzbd.webp